In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('../datasets/Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

# encoding categorical data
x_transformer = ColumnTransformer(
    [
        ('geography_encoded', OneHotEncoder(), [1]),
        ('gender_encoded', OneHotEncoder(), [2]),
    ],
    remainder='passthrough'
)
X = x_transformer.fit_transform(X)

# dropping one of the dummy variables for each encoded variable (geography and gender) 
X = np.concatenate((X[:, 1:3], X[:, 4:]), axis=1)
X

array([[0.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 1.0, 0.0, ..., 0, 1, 112542.58],
       [0.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [1.0, 0.0, 1.0, ..., 1, 0, 92888.52],
       [0.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [20]:
# applying feature scaling
from sklearn.preprocessing import StandardScaler

x_scaler = StandardScaler()
X = x_scaler.fit_transform(X)
X

array([[-0.57873591, -0.57380915, -1.09598752, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-0.57873591,  1.74273971, -1.09598752, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-0.57873591, -0.57380915, -1.09598752, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [-0.57873591, -0.57380915, -1.09598752, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.72790383, -0.57380915,  0.91241915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [-0.57873591, -0.57380915, -1.09598752, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [21]:
# splitting data into training and test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [24]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [75]:
# initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(input_dim=11, output_dim=500, init='uniform', activation='relu'))
# Adding the second hidden layer
classifier.add(Dense(output_dim=500, init='uniform', activation='relu'))
# Adding the third hidden layer
classifier.add(Dense(output_dim=500, init='uniform', activation='relu'))
# # Adding the fourth hidden layer
classifier.add(Dense(output_dim=500, init='uniform', activation='relu'))
# # Adding the fifth hidden layer
classifier.add(Dense(output_dim=500, init='uniform', activation='relu'))
# Adding the output layer
classifier.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))

# Compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

/home/matus/documents/machine_learning/venv/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, activation="relu", units=500, kernel_initializer="uniform")`
  """
/home/matus/documents/machine_learning/venv/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=500, kernel_initializer="uniform")`
  import sys
/home/matus/documents/machine_learning/venv/lib/python3.7/site-packages/ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=500, kernel_initializer="uniform")`
  if __name__ == '__main__':
/home/matus/documents/machine_learning/venv/lib/python3.7/site-packages/ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=500, kernel_initializer="uniform")`
  # This is added back by InteractiveShellApp

In [76]:
classifier.fit(X_train, y_train, batch_size=100, epochs=50)

Epoch 1/50
8000/8000 [==============================] - 2s 253us/step - loss: 0.4531 - accuracy: 0.7980
Epoch 2/50
8000/8000 [==============================] - 2s 207us/step - loss: 0.3647 - accuracy: 0.8533
Epoch 3/50
8000/8000 [==============================] - 2s 209us/step - loss: 0.3479 - accuracy: 0.8586
Epoch 4/50
8000/8000 [==============================] - 2s 210us/step - loss: 0.3388 - accuracy: 0.8630
Epoch 5/50
8000/8000 [==============================] - 2s 207us/step - loss: 0.3330 - accuracy: 0.8649
Epoch 6/50
8000/8000 [==============================] - 2s 209us/step - loss: 0.3310 - accuracy: 0.8661
Epoch 7/50
8000/8000 [==============================] - 2s 207us/step - loss: 0.3250 - accuracy: 0.8673
Epoch 8/50
8000/8000 [==============================] - 2s 218us/step - loss: 0.3193 - accuracy: 0.8700
Epoch 9/50
8000/8000 [==============================] - 2s 215us/step - loss: 0.3147 - accuracy: 0.8736
Epoch 10/50
8000/8000 [==============================] - 2s 223u

In [77]:
from sklearn.metrics import confusion_matrix
import math

y_pred = classifier.predict(X_test)

cm = confusion_matrix(y_test, [int(round(y[0])) for y in y_pred])
print(f'accuracy: {(cm[0][0] + cm[1][1]) / len(y_pred)}')
print(cm)

accuracy: 0.826
[[1425  170]
 [ 178  227]]
