In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
style.use('ggplot')

In [2]:
df = pd.read_csv('../datasets/Wine.csv')
df.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [4]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [22]:
# Apply PCA
from sklearn.decomposition import PCA

pca = PCA(n_components=None)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_

In [23]:
explained_variance

array([0.36722576, 0.19231879, 0.10830194, 0.07414597, 0.06288414,
       0.05059778, 0.0419487 , 0.02518069, 0.02222384, 0.01858596,
       0.01712304, 0.01277985, 0.00668354])

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
X_train

array([[-2.21627675, -0.99947455],
       [-1.76925781,  1.61300784],
       [ 1.17230703,  2.17064305],
       [-2.6014977 , -1.609546  ],
       [ 1.86604905,  0.25746789],
       [ 2.49349602, -1.37197296],
       [ 0.99055658,  2.21283977],
       [-0.31170514,  2.33942943],
       [-0.27666207,  2.28546079],
       [ 2.14355466, -1.13229538],
       [-3.01518615, -0.22042782],
       [ 1.97545232,  1.23483092],
       [-2.14836544, -0.97737265],
       [ 2.11177177, -2.38185703],
       [-2.27974752, -0.17171001],
       [-3.02367296, -0.22662921],
       [ 2.61693584, -0.96025772],
       [-1.19962285, -3.60637471],
       [ 2.63283998, -0.01968345],
       [ 0.29070953,  2.22881352],
       [-2.7250823 , -2.59097738],
       [-2.54768702, -0.38218125],
       [ 1.78508956,  0.84083107],
       [-2.80389949, -0.34883473],
       [-2.88844587, -1.8830148 ],
       [ 1.33095558,  0.05053056],
       [-2.45255261,  0.14391294],
       [-2.28093414,  0.52369861],
       [ 1.26560815,

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

classifier = LogisticRegression()
classifier.fit(X_train, y_train)
print(f'accuracy {classifier.score(X_test, y_test)}')

cm = confusion_matrix(y_test, classifier.predict(X_test))
cm

accuracy 0.9722222222222222


array([[14,  0,  0],
       [ 1, 15,  0],
       [ 0,  0,  6]])