In [2]:
import numpy as np

In [7]:
# implementation of naive_add of 2D tensors
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape

    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(y.shape[0]):
            x[i, j] += y[i, j]
    return x

In [8]:
x = np.array([[1, 2],
              [2, 3]])
y = np.array([[2, 3],
              [4, 5]])

print(naive_add(x, y))
print()
print(x + y)

[[3 5]
 [6 8]]

[[3 5]
 [6 8]]


In [12]:
# implementation of naive add matrix and vector
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2 # 2D tensor
    assert len(y.shape) == 1 # 1D tensor
    assert x.shape[1] == y.shape[0]
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

In [14]:
x = np.array([[1, 2, 3],
              [2, 3, 4],
              [5, 6, 7]])
y = np.array([1, 1, 1])
print(naive_add_matrix_and_vector(x, y))
print()
print(x + y)

[[2 3 4]
 [3 4 5]
 [6 7 8]]

[[2 3 4]
 [3 4 5]
 [6 7 8]]


In [15]:
# implementation of naive vector dot
def naive_vector_dot(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    
    sum_ = 0
    for i in range(x.shape[0]):
        sum_ += x[i] * y[i]
    return sum_

In [17]:
x = np.array([1, 2, 3])
y = np.array([2, 3, 4])
print(naive_vector_dot(x, y))

20


In [26]:
def naive_matrix_vector_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = naive_vector_dot(x[i], y)
    return z

In [27]:
x = np.array([[1, 2, 3], 
              [2, 3, 4]])
y = np.array([2, 2, 2])
naive_matrix_vector_dot(x, y)

array([12., 18.])

In [33]:
def naive_matrix_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros((x.shape[0], y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i, :]
            col_y = y[:, j]
            z[i, j] = naive_vector_dot(row_x, col_y)
    return z

In [35]:
x = np.array([[1, 2, 3], 
              [2, 3, 4]])
y = np.array([[1, 2], 
              [1, 2],
              [1, 2]])
print(naive_matrix_dot(x, y))
print()
print(x.dot(y))

[[ 6. 12.]
 [ 9. 18.]]

[[ 6 12]
 [ 9 18]]
